// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Agreement struct {
	ID        string `json:"id"`
	Topic     string `json:"topic"`
	RoleID    int    `json:"roleId"`
	ChannelID int    `json:"channelId"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type Alert struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Measure     string `json:"measure"`
	Threshold   int    `json:"threshold"`
	BudgetID    int    `json:"budgetId"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type Backup struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type Bucket struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Class       int    `json:"class"`
	Stage       int    `json:"stage"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type Budget struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	Reference  string `json:"reference"`
	Term       string `json:"term"`
	Amount     int    `json:"amount"`
	Correction int    `json:"correction"`
	CreatedAt  string `json:"createdAt"`
	UpdatedAt  string `json:"updatedAt"`
}

type Channel struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	Description    string `json:"description"`
	Class          int    `json:"class"`
	Stage          int    `json:"stage"`
	Service        string `json:"service"`
	Address        string `json:"address"`
	AlertID        int    `json:"alertId"`
	NotificationID int    `json:"notificationId"`
	CreatedAt      string `json:"createdAt"`
	UpdatedAt      string `json:"updatedAt"`
}

type Class struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type Db struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Class     int    `json:"class"`
	Stage     int    `json:"stage"`
	Secret    string `json:"secret"`
	SizeID    int    `json:"sizeId"`
	BackupID  int    `json:"backupId"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type Domain struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type Filesystem struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Class       int    `json:"class"`
	Stage       int    `json:"stage"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type Internetgateway struct {
	ID                string `json:"id"`
	Name              string `json:"name"`
	Description       string `json:"description"`
	InternetGatewayID string `json:"internetGatewayId"`
	VpcID             string `json:"vpcId"`
	CreatedAt         string `json:"createdAt"`
	UpdatedAt         string `json:"updatedAt"`
}

type Movie struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	URL         string `json:"url"`
	ReleaseDate string `json:"releaseDate"`
}

type NewAgreement struct {
	Topic     string `json:"topic"`
	RoleID    int    `json:"roleId"`
	ChannelID int    `json:"channelId"`
}

type NewAlert struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Measure     string `json:"measure"`
	Threshold   int    `json:"threshold"`
}

type NewBackup struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type NewBucket struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type NewBudget struct {
	Name       string `json:"name"`
	Reference  string `json:"reference"`
	Term       string `json:"term"`
	Amount     int    `json:"amount"`
	Correction int    `json:"correction"`
}

type NewChannel struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Class       int    `json:"class"`
	Stage       int    `json:"stage"`
	Service     string `json:"service"`
	Address     string `json:"address"`
}

type NewClass struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type NewDb struct {
	Name   string `json:"name"`
	Secret string `json:"secret"`
}

type NewDomain struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type NewFilesystem struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type NewInternetgateway struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	VpcID       string `json:"vpcId"`
}

type NewMovie struct {
	Title string `json:"title"`
	URL   string `json:"url"`
}

type NewNotification struct {
	Control string `json:"control"`
	Scope   string `json:"scope"`
}

type NewPrivilege struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Scope       string `json:"scope"`
}

type NewResident struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type NewRole struct {
	DomainID int `json:"domainId"`
	TaskID   int `json:"taskId"`
	Class    int `json:"class"`
	Stage    int `json:"stage"`
}

type NewRouteTable struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	VpcID       string `json:"vpcId"`
}

type NewSize struct {
	Name    string `json:"name"`
	Cores   int    `json:"cores"`
	Storage int    `json:"storage"`
}

type NewStage struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type NewSubnet struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	CidrBlock   string `json:"cidrBlock"`
	VpcID       string `json:"vpcId"`
}

type NewTask struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	PrivilegeID int    `json:"privilegeId"`
}

type NewVpc struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	CidrBlock   string `json:"cidrBlock"`
}

type Notification struct {
	ID        string `json:"id"`
	Control   string `json:"control"`
	Scope     string `json:"scope"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type Privilege struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Scope       string `json:"scope"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type Resident struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Account     string `json:"account"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type Role struct {
	ID        string `json:"id"`
	DomainID  int    `json:"domainId"`
	TaskID    int    `json:"taskId"`
	Class     int    `json:"class"`
	Stage     int    `json:"stage"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type RouteTable struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	Description  string `json:"description"`
	RouteTableID string `json:"routeTableId"`
	VpcID        string `json:"vpcId"`
	CreatedAt    string `json:"createdAt"`
	UpdatedAt    string `json:"updatedAt"`
}

type Size struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Cores     int    `json:"cores"`
	Storage   int    `json:"storage"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type Stage struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type Subnet struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	SubnetID    string `json:"subnetId"`
	CidrBlock   string `json:"cidrBlock"`
	VpcID       string `json:"vpcId"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type Task struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	PrivilegeID int    `json:"privilegeId"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type Vpc struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CidrBlock   string `json:"cidrBlock"`
	VpcID       string `json:"vpcId"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}
